### ISSUE TITLE
Guake not work on Ubuntu 17.10

### ISSUE THREAD

**Issue by omidraha** [Guake/guake#1024]
Sometimes Guake not start, and after with some delay just show me one hanged blank page, as this picture:

![guake_blank_page](https://user-images.githubusercontent.com/397672/32403818-d3be763a-c158-11e7-8c06-5c8df59be586.png)

The traceback:
```
(guake:4774): libglade-WARNING **: unknown attribute `swapped' for <signal>.
INFO:guake.guake_app:Logging configuration complete
INFO:guake.notifier:Notification service is not running (yet). Guake can't display notifications!
  We'll retry a few times more a bit later, but you can use
  the following command to disable the startup notification:
$ gconftool-2 --type bool --set /apps/guake/general/use_popup false
/usr/lib/python2.7/dist-packages/guake/guake_app.py:865: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DOCK)
/usr/lib/python2.7/dist-packages/guake/guake_app.py:866: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_NORMAL)

```

Then i turn off notification:

`$ gconftool-2 --type bool --set /apps/guake/general/use_popup false`

And run it again, Guake run some times successfully, but there is also this traceback:

```
(guake:5183): libglade-WARNING **: unknown attribute `swapped' for <signal>.
INFO:guake.guake_app:Logging configuration complete

/usr/lib/python2.7/dist-packages/guake/guake_app.py:865: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DOCK)
/usr/lib/python2.7/dist-packages/guake/guake_app.py:866: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_NORMAL)

```

Info:
```
or@or:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 17.10
Release:        17.10
Codename:       artful
or@or:~$ uname -a
Linux or 4.13.0-16-lowlatency #19-Ubuntu SMP PREEMPT Wed Oct 11 19:51:52 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
`Guake Terminal 0.8.8`

**Comment by Stibbons** [comment]
I think we can agree guake 0.8 is to be depreciated. I am working on guake 3 to release an initial version supporting gtk3 asap

**Comment by aichingm** [comment]
Guake has some code in place to test if it runs on ubuntu and if so it would do some magic which is needed to make guake work with unity and libappindicator. Since ubuntu switched back to gnome in the 17.10 release this code needs to be removed (or at least modified).  

* The unity code is obsolete and broken!
* I don't know about libappindicator (does gnome use any of it or could libnotify be used instead, like on quite all other DEs?)

[unity](https://github.com/Guake/guake/blob/d2c0c3d1b1e18adf58a43f0c19941d26ba1130b3/src/guake/guake_app.py#L997)
[unity](https://github.com/Guake/guake/blob/d2c0c3d1b1e18adf58a43f0c19941d26ba1130b3/src/guake/guake_app.py#L1002)

[appindicator](https://github.com/Guake/guake/blob/d2c0c3d1b1e18adf58a43f0c19941d26ba1130b3/src/guake/guake_app.py#L182)

**Comment by Stibbons** [comment]
Let's drop it or make it in a plugin

**Comment by Moritz90** [comment]
Please don't remove the app indicator support. Since support for the "old" status icons will be removed from GNOME, the indicator shell extension will become the only way to show a status icon when guake is running.

**Comment by Stibbons** [comment]
Can you try with the latest HEAD?

**Comment by Stibbons** [comment]
I close it as no more relevant for guake 3. Guake 0.8 will no more be maintained actively but I will review pull requests
