### ISSUE TITLE
Option/keystroke to clear scrollback lines

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#104]
Option/keystroke to clear scrollback lines http://guake.org/ticket/402
Reported by:    analogkid   Owned by:   somebody
Priority:   major   Milestone:  0.5.0
Component:  guake   Version:  
Keywords:       Cc:  
Description

Like in gnome-terminal, Ctrl-L works for clearing the screen, but it doesn't actually clear the scrollback lines. Could a simple keystroke be implemented for this? Like "Reset and Clear" in gnome-terminal. This would improve security/privacy if someone were to stumble across your computer while you're away.

The alternative, Ctrl-Shift-W, will close the tab and clear the scrollback history, but it's a little inconvenient.

**Comment by tavlima** [comment]
I didn't know about the reset ncurse utility and it's really cool, but it would be nice to have a shortcut for the same feature in Guake, like the "reset and clear" option in Gnome Terminal. I'm used to "reset&clear" my terminal while reading logs and dumping data, which is impossible in Guake since I need to run the "reset" command.

+1

**Comment by thardev** [comment]
Hello @Stibbons I suggest to close this because this feature was recently implemented in the issue #614 :+1:
