### ISSUE TITLE
Commands/--opts for changing 256 color scheme

### ISSUE THREAD

**Issue by SoniEx2** [Guake/guake#1043]
Can we get commands for changing the 256 color scheme of a given tab? Thanks.

Something along the lines of `--setcolors index:value[/index:value...]`.

**Comment by egmontkob** [comment]
If Guake finally switched to gtk3 (wink wink), you could use the OSC 4 escape sequences, e.g. `echo -ne '\e]4;16;#abcdef\a'`.

**Comment by SoniEx2** [comment]
Why not both? Do the easy one first, then the hard one later?

**Comment by egmontkob** [comment]
> Why not both? Do the easy one first, then the hard one later?

I'm not a Guake developer and hence cannot answer this, but:

The easy one, no matter how easy is, would be beneficial to one of your friends, and probably hardly anyone else. (Unlike the first 16 colors, the rest of the 256-color palette is the same in every terminal emulator by default. So far I've only seen one case where this palette was redefined. I believe if these default colors aren't good enough for someone, they should be going for real truecolor support rather than changing this palette.)

The hard one would be beneficial to pretty much all the users. Just look at VTE's changelog for how many security/privacy/bug/datacorruption-fixes and other improvements went into it during the last few years, which you don't get with Guake since it's stuck with an ancient unmaintained and quite buggy version thereof.

The hard method is indeed much harder, but despite that, it still has a much better gain:investment ratio.

Unfortunately as long as Guake is stuck with an old VTE, I wouldn't recommend this terminal emulator to anyone.

**Comment by SoniEx2** [comment]
Hmm, ok! So what's the open issue for gtk3?

**Comment by egmontkob** [comment]
It's issue 1009, looks quite promising now :)

**Comment by Stibbons** [comment]
I close this as a non guake feature, it will not be supported out of the box BUT it is on the verge of being completely running on gtk3 :)

**Comment by SoniEx2** [comment]
I was literally gonna close it myself :<
