### ISSUE TITLE
guake creates zombie process on gnome

### ISSUE THREAD

**Issue by taiak** [Guake/guake#1108]
i use Guake Terminal 0.8.8. When guake start, gsettings not finish.
it see like https://github.com/Guake/guake/issues/636 but it's still zombie process. When i disable "use the system fixed width font", there is no problem.
![guake zombie](https://user-images.githubusercontent.com/15039423/35128070-cbd62730-fcc5-11e7-9c23-9cee7982218c.png)

**Comment by zelurker** [comment]
You can fix this with a single python line, I just did it on my system. It's in the gconfhandler.py file, located for me in /usr/lib64/python2.7/site-packages/guake/gconfhandler.py, just add
proc.stdout = proc.communicate()
after the line
proc = subprocess.Popen(['gsettings', 'get', DCONF_MONOSPACE_FONT_PATH,
                                     DCONF_MONOSPACE_FONT_KEY], stdout=subprocess.PIPE)
if you do it manually on an installed version, you might want to recompile the file :
cd /usr/lib64/python2.7/site-packages/guake
python -m compileall gconfhandler.py
and 
python -O -m compileall gconfhandler.py
Worked for me... !

**Comment by taiak** [comment]
Sorry but i don't have /usr/lib64/python2.7/site-packages/guake/gconfhandler.py file 
but i have /usr/lib/python2.7/dist-packages/guake/gconfhandler.py and it's work. Thank dude

**Comment by zelurker** [comment]
Sorry also on my side, I did that late in the night and didn't take time to
test the code.
It actually fails on the gsettings handling but in this case the default
behavior is clearly enough for us.
Anyway the reason is that communicate() does all the process handling by
itself and returns strings instead of streams.
So the correct code is this :
            proc = subprocess.Popen(['gsettings', 'get',
DCONF_MONOSPACE_FONT_PATH,
                                     DCONF_MONOSPACE_FONT_KEY],
stdout=subprocess.PIPE)
            proc.stdout,stderr = proc.communicate()
            font_name = proc.stdout.replace("'", "")
            if font_name is None:
                # Back to gconf
                font_name = client.get_string(GCONF_MONOSPACE_FONT_PATH)
        else:
(proc.kill disappears because it's handled by communicate, as well as
stdout.readline() because it's now already a string).
Sorry again !


2018-03-05 2:07 GMT+01:00 Taha Yasir Kıroğlu <notifications@github.com>:
