### ISSUE TITLE
Main Window Horizontal Alignment

### ISSUE THREAD

**Issue by thomasave** [Guake/guake#1116]
All radio buttons seem to be selected by default. 
This results in only the Center option actually working and the user not being able to select a different option.
![screenshot from 2018-01-20 11-28-45](https://user-images.githubusercontent.com/8020909/35182528-17ab42c8-fdd7-11e7-9cdf-c241f9610e7f.png)
I need this option because by default Guake overlaps with Dash to Dock.
I run the latest version on master (3.0.3)

**Comment by egmontkob** [comment]
Yup I can confirm this behavior.

A weak UI note: "Prompt on close tab" on this page, as well as cursor stuff on Appearance and the del/backspace stuff on Compatibility are three-state comboboxes. So for a more consistent UI, instead of fixing the radiobuttons, going for a combobox might be a nice idea here.

A stronger UI note: There's Placement -> Bottom align window instead of top align, and there's Main Window Horizontal Alignment -> this option. These two seem to be as closely related as possible, hence IMHO should be under the same subsection, next to each other, and should use the same UI. Which could be to convert top/bottom into a two-state radiobutton, or convert both to comboboxes.

And while at it, yet another weak one: similarly to this option, it's a bit weird to me that Main Window Width/Height are also options that have a bold section title only (one per each) and no normally typeset label.
