### ISSUE TITLE
[gtk3] Keyboard shortcut innocent warnings

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1143]
This is printed to stderr once when opening the prefs window (path chopped by me):

```
[...]/prefs.py:671: Warning: unable to set property 'accel-key' of type 'guint' from value of type 'gchararray'
  self.get_widget('config-window').show_all()
[...]/prefs.py:671: Warning: unable to set property 'accel-mods' of type 'GdkModifierType' from value of type 'gchararray'
  self.get_widget('config-window').show_all()
```

and this is once when switching to the "Keyboard shortcuts" tab for the first time:

```
[...]/main.py:341: Warning: unable to set property 'accel-key' of type 'guint' from value of type 'gchararray'
  Gtk.main()
[...]/main.py:341: Warning: unable to set property 'accel-mods' of type 'GdkModifierType' from value of type 'gchararray'
  Gtk.main()
```

They look quite innocent, I mean I didn't notice any faulty behavior these would correspond to.

**Comment by Stibbons** [comment]
I agree, but if I remove the `add_attribute` that seems to trigger this behavior, it does not work anymore.

**Comment by Davidy22** [comment]
Looks like some internal typing nonsense inside pygobject. No way to actually cast a guint with the gi interface, there is a way to cast a Gdk.ModifierType(), but that immediately gets recast internally in pygobject and the same message is thrown. Ultimately doesn't affect functionality, pygobject figures it out internally eventually. Probably should be raised as an issue to pygobject, but probably similarly non-urgent there since it otherwise works despite the message.
