### ISSUE TITLE
Release before new Split-Terminal feature?

### ISSUE THREAD

**Issue by aichingm** [Guake/guake#1411]
Hey @gsemet,

I'm done implementing #71.

Two questions:

1. As of now I would consider guake pretty stable. Since the new feature changes a lot of code again I thought maybe it is a good idea to  to release a current version.

2. Have you seen the bounty over on <https://www.bountysource.com/issues/1324038-split-terminal-functionnality>? Some one should claim it... (I would like to :stuck_out_tongue_winking_eye: , BTW who is paying for the domain <http://guake-project.org/>?)

* Splitting as deep as you want
* Resize the split area with the mouse
* New context menu entries for splitting and closing terminals
![image](https://user-images.githubusercontent.com/6470959/45783029-f3553800-bc64-11e8-9bc1-f8d917aa536c.png)

Keybindings for:
* Splitting horizontal and vertical
* Moving the focus to the terminal above, below, left, or right
* Resizing the terminals up, down, left and right
* Closing a terminal 
![image](https://user-images.githubusercontent.com/6470959/45785361-45e62280-bc6c-11e8-8e44-f73faa729d4f.png)

**Comment by gsemet** [comment]
Seem really cool ! Thanks for your work :)

Yes the bounty has just got 250$ a few days ago, I have no idea who is behind and even if it will work. So to answer you short: YES, I see no problem if you claim the bounty for your really helpful work the last months, this terminal backend rework enabling the split terminal and of course the GTK3 transition.

But I would be happy if you can consider a donation to the Guake project :) I am the one for the guake-project.org domain and hosting. Please contact me to my mail :)

I just release [3.3.3](https://github.com/Guake/guake/releases/tag/3.3.3) as a small release since most changes are under the hood. So when you land your split terminal feature, so not forget the `sem-ver: feature` tag in your commit message.

I like the context menu entry, much like iterm2 does. Does it also support drag and droping the terminal to reorganize the notebook terms?

**Comment by aichingm** [comment]
>  But I would be happy if you can consider a donation to the Guake project :) I am the one for the guake-project.org domain and hosting. Please contact me to my mail :)

Yes, of course! I was thinking about a 50/50 split, since all I have done would be more or less useless without the work you have done for example on the build system.

There is no drag & drop support at the moment. I have to look in to drag & drop mechanisms in GTK.
