### ISSUE TITLE
Feature Request: Word search

### ISSUE THREAD

**Issue by johnny-mac** [Guake/guake#1441]
Hello! I had this idea today, I imagine its been thought of or suggested before though, it would be really helpful to be able to search for text in the guake terminal, like what falkon & gedit have when you click CTRL+F. 

I love this terminal, its simply the best, by a long-shot! Thank you for all the work you do! I learned how to use a command line in guake when I first started using Linux years ago! 

Edit:
Would it help if I found you a python program that has a search function like that already implemented perhaps? More than happy to do anything I can to help you!

**Comment by gsemet** [comment]
hi. It is one of the long awaiting feature you can have a look if you want :) If you dig a little in the source you ll see some parts are ready for this feature (I even started the dialog box), but I think something like "iterm2" search feature would be cool (a small panel appears on top/botton of the current terminal (not the window, the terminal since we have split tab now), and allow to search in the terminal (default search direction is backward)

**Comment by Davidy22** [comment]
Resolved, closing.
