### ISSUE TITLE
Guake won't start on Ubuntu 16.04

### ISSUE THREAD

**Issue by alekslauda** [Guake/guake#1470]
![image](https://user-images.githubusercontent.com/5708804/49650761-0393dc80-fa36-11e8-8f92-c0d1f9ee961f.png)
What can i do , any idea ?

**Comment by mobusdorphin** [comment]
Looks like you're missing the GObject Introspection library.  Make sure gobject packages are installed (since it seems you're using ubuntu - `sudo apt-get install python3-gi` ).  If it is installed, make sure your default python is pointing to the correct place.  

See this stackoverflow thread for more information: https://askubuntu.com/questions/80448/what-would-cause-the-gi-module-to-be-missing-from-python

**Comment by alekslauda** [comment]
![image](https://user-images.githubusercontent.com/5708804/50109547-d23ebc00-0240-11e9-9f30-358af5cc88a0.png)
I've installed it , and research a lot in the net about the problem , but still couldnt manage to solve it :(

**Comment by aichingm** [comment]
@alekslauda how did you install guake? How did guake end up in the python 2.7 site packages folder? Guake is python 3 only.

**Comment by zpeleg** [comment]
Looks like it was installed using `pip install guake`, you should `pip3 install --user guake`.

**Comment by alekslauda** [comment]
![image](https://user-images.githubusercontent.com/5708804/53861113-d41c4e00-3feb-11e9-8172-c652420567f7.png)

**Comment by gsemet** [comment]
... so install keybinder... or read the install section of the documentation...
