### ISSUE TITLE
Where did the button go?

### ISSUE THREAD

**Issue by johnny-mac** [Guake/guake#1471]
The button for making new tabs has vanished as of the last update.... What gives? Where'd the button go?

**Comment by amezin** [comment]
Also, can't open new tab by double-clicking on the free space of tab bar

**Comment by amezin** [comment]
This button and the double-click behavior was literally the only reason why I was using Guake instead of, for example, tilda

**Comment by johnny-mac** [comment]
we can use ctrl+shift+T, but I'd still like to know why the button is gone...

**Comment by gserrg** [comment]
+1

**Comment by Zjemm** [comment]
same here, would like it back

**Comment by Archcry** [comment]
Well, something that works for you doesn't necessarily work for everyone :P It would be nice to have the choice (in the settings?) to turn the button on.

**Comment by gserrg** [comment]
Do you also make a selection with a keyboard? I also use the keyboard for everyday work, but there are cases when the mouse is already in your hand and reach for the keyboard longer than you click.

**Comment by aichingm** [comment]
From @johnny-mac 
> we can use ctrl+shift+T, but I'd still like to know why the button is gone...

### Since I was the person who removed the button here is why (+ a little bit of history): 

***Note**: when I speak about a notebook I mean the Gtk widget.*



As of Guake 0.8.x (which was the version is started contributing to Guake), Guake had a custom implementation of the Gtk's notebook-tab-bar: https://github.com/Guake/guake/blob/0.8.x/src/guake/guake_notebook.py which looked like this:

![image](https://user-images.githubusercontent.com/6470959/50688437-cbc48880-1025-11e9-9904-e7200c3bb1a9.png)

![image](https://user-images.githubusercontent.com/6470959/50688465-e139b280-1025-11e9-8fd7-f75aa1e515f5.png)

The good things about it were:

-  The size of the tab-bar could be adjusted to make room for the add-tab-button on right side. 
- More possibilities to set custom click listeners to add double-click-on-empty-space-to-add-tab functionally.

The negatives were: 

- Reordering had to be implemented by Guake itself. 
- Scrolling had to be implemented by Guake itself. 
- Highlighting had to be implemented by Guake itself. 
- Adding and removing new tabs had to be implemented by Guake itself. 
- Menus had to be implemented by Guake itself. 
- Changing tabs had to be implemented by Guake itself. 
- The custom implementation was not themed to fit in to the whole Gtk3 ecosystem and bringing it to this point would have been a s*** load of work.

And for all of this custom implementations they had to be reworked once in a while to stay on par with Gtk2/3/4. 

As of the time when I ported Guake from Gtk2 to Gtk3 (Guake 3.0.0) I just ported the whole custom implementation so that it was part of Guake until I started working on https://github.com/Guake/guake/commit/1311cb0b6b16952ebddf766d75576146f45dc218 which was in my opinion necessary to get to a code base upon which the split-terminal (and now the per workspace) functionality could be implemented (a big need was to enable more than just one terminal per notebook page). 

With the reimplementation of the notebook (https://github.com/Guake/guake/commit/1311cb0b6b16952ebddf766d75576146f45dc218) to a more on the default Gtk3 based approach a lot of code was removed from Guake, which made the code base more maintainable and future proof (see new features) (there even was this issue: https://github.com/Guake/guake/issues/1375). But this meant that some of the benefits of a custom implementation where also removed fo example the ability to place a button next to the notebook's tab bar. I my opinion moving to a default implementation brought much more benefits to Guake then we lost in the transition, so I went with it. 


From @Archcry 
> Seems to be part of a new design or something? I'd like to see the button back though.

It wasn't so much of a design decision but more a maintainability decision, even tho by using more of Gtk's components the design got more close to the upstream design philosophy.


To address the point of bringing it back: I understand that people used the button and would like to use it again, I personally haven't used it ever, since I'm a vary keyboard driven user. I don't have an easy solution to this problem other than bringing back a custom implementation (which I don't think anyone would want to maintain).

Currently there are two ways to open a new tab one would be hitting the keys `ctrl`+`shift`+`t` (which you can change to what ever you want) or to right-click on to an open tab and choose "New Tab" from there, which is just one little right-click more than the button was PLUS the target is now bigger since you can right click on any tab.

![image](https://user-images.githubusercontent.com/6470959/50690877-46de6c80-102f-11e9-89ab-9d9777f45915.png)

**Comment by gsemet** [comment]
i am ok for adding the + button. thanks for this contribution !

**Comment by gsemet** [comment]
fixed on head
