### ISSUE TITLE
Dual monitor snapping

### ISSUE THREAD

**Issue by Archcry** [Guake/guake#1473]
Since the last patch the terminal is no longer opened on the same screen the cursor is present. It seems to just open on the screen opposite to where it was last opened. So for example, when guake was open on screen 0 it will open on screen 1 and vise versa.

Edit: I just downgraded to version 3.3.2-2 and the issue is not present there. I'm ignoring package upgrades for now.

**Comment by danilobellini** [comment]
Same issue here (on Arch Linux), and I've downgraded to the same version as well.

The exact behavior with two displays (primary as `0`) is:

- If the cursor is in `0`, always open Guake on `0`;
- If the cursor is in `1`, alternate (toggle to the display distinct from the last one where Guake was shown).

**Comment by PavelSmokorovskiy** [comment]
Here is the solution https://github.com/Guake/guake/issues/1453

**Comment by Archcry** [comment]
I can confirm this issue is solved in later versions of guake. I installed guake-git from the arch user repository instead of the official guake package from the official arch repositories. Closing this because of that reason.

**Comment by mart-st-manov** [comment]
Looks like the issue is back (or never fixed). Using Mint 19.1 and I manually upgraded from version 3.0.5 to 3.6.3 because of a different issue (still not fixed).

On a laptop setup with an external monitor the first time opening guake it is on the correct screen. Every time after that it opens on the laptop screen even though I've setup the default screen to be the external one in the system settings. Reverted back to the default ppa and version 3.0.5 since it's less buggy.
