### ISSUE TITLE
Some fixes for Session Save and search

### ISSUE THREAD

**Issue by gsemet** [Guake/guake#1536]
So first, I am very graceful for you work, @mlouielu. I made some changes in the code, and I have some idea to increase even better these two features. Do you think you can look at these:

Session
- make save the session the default (so we have no action to have session automatically saved upon Guake close). Maybe add a checkbox in preference to disable this behavior.
- add load/save tabs item in main menu (the context menu displayed in terminal)
- add a warning yes/no dialog before restoring, telling user his terminal might be replaced.
- and replaced (no "add") terminal when doing a "restore" session

Search:
- I like the "iterm2" loop, when you reach the end or top, you look to the other side of the terminal with a message saying your did a "loop". 
- Also, when there is only 1 item that matched, the selection should not change when I go to next. Here it seem to disable everything if I hit "next" button (or enter) after the first (and only selection)

I have a bug when I close any tab (right click, close), the terminal is closed but the tab stay empty opened, do you have it? I have this since the big rework on the notebook, and I need to fix it before releasing next version of guake!

**Comment by mlouielu** [comment]
Session
* Sure, just change it to default
* I've already put a save/restore menu item in context menu one (right click on the tabbar)
* Yes, but I think this only need when the user is restore from clicking menu item? Or do we need to warn user when they startup the Guake?
* Currently it remove the page and re-add it, so you think it should remove the terminal in page, and re-add into it? or how to replace it, can you elaborate that?

Search:
* I believe this is related to Vte, not sure if we can do it or not
* Yep, we will need to record if it found a match first, and if the next match failed, it will call search_prev so that the highlight will be on it. But I think the button should remain disabled when it is in the end, to indicate user it is at the end of the search
* If we really want to loop over, we will need to work around (e.g. get all text from terminal out and search it first), or fixed upstream Vte code...

For the close tab issue, I think is related to revert 4ba0b2abcb in #1515, can you test to add back `self.remove_page(page_num)` to test it? But then it may trigger #1513

**Comment by gsemet** [comment]
> Yes, but I think this only need when the user is restore from clicking menu item? Or do we need to warn user when they startup the Guake?
only by the menu item, on startup we expect to restaure everything silently

> Currently it remove the page and re-add it, so you think it should remove the terminal in page, and re-add into it? or how to replace it, can you elaborate that?
My idea is just to remove everything and reset the complete session. So we need to warn the user current tabs will be changed. Now when I do a restore it actually appends tabs to existing one (or maybe there is a bug)

hum for the loop, there is no "caret" position in the search?

**Comment by gsemet** [comment]
I see two bugs with "search":
- if I do "Ctrl+Shit+F", and start typing my word, each time I hit a key the search advance to the next occurence, even if the current selection could just be extended
- if I do "Ctrl+Shift+F" + type some character and then hit enter, the search does not go backward. I need to hit "Shift-enter". I would prefer to mimick iterm2 behavior and search backward by default. Shift+Enter search fro top to bottom, and enter from bottom to top

**Comment by gsemet** [comment]
Also: hide on focus kind of close the search box, I would prefer to keep it opened and capture the escape shortcut to close it, or Ctrl+Shift+F again to close the search box

**Comment by mlouielu** [comment]
So we have two remain to do
- [ ] default true for saving tabs when changed
- [ ] replace the tabs

I choice to add the tabs first, then remove the original tabs is because, it will be unable to remove the page when it left the last page in the notebook, so add the tabs first then remove can prevent this problem. Or do we just remove the notebook from workspace, and re-create another one?

**Comment by gsemet** [comment]
can you try creating a new notebook and then kind of switch it when ready?
