### ISSUE TITLE
'Bold text is also bright' option not detected on new session/tab when disable

### ISSUE THREAD

**Issue by henrythebuilder** [Guake/guake#1625]
Hi,
 I have a small problem with 'Bold text is also bright' option.
When the option is disabled the text appears as expected, but opening a new tab or restart a new session text appears as if it was enabled (despite being disabled in the configuration).
Re-enable and disable the option from preference causes an automatic refresh in Guake and the text appears as expected. Same result if the option is enable (true) and disable (false) from dconf editor.
Sorry for the small problem reported, it certainly does not affect the functionality of Guake, but I couldn't find a solution.
Thank in advance for your work.
Enrico

```
System info: 
Debian 10.0 - Buster Release
Architecture: amd64 (x86_64)

Guake info (installed from Pypi):
Guake Version:		3.6.3
Vte Version:		0.54.2
Vte Runtime Version:	0.54.2
--------------------------------------------------
GTK+ Version:		3.24.5
GDK Backend:		GdkX11.X11Display
--------------------------------------------------
Desktop Session: cinnamon (Version: 3.8.8-1)
--------------------------------------------------
Display: :0
RGBA visual: True
Composited: True
* Monitor: 0 -  LVDS-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		344 x 193 mm²
    * Primary:		True
    * Refresh rate:	60.01 Hz
    * Subpixel layout:	horizontal-rgb
```

**Comment by egmontkob** [comment]
`gsettings.py` (this is used when toggling the settings) unconditionally calls `set_bold_is_bright()` (in a try-except block to ignore if VTE doesn't support it yet).

`terminal.py` (this is used when starting up a new terminal) on the other hand only calls `set_bold_is_bright()` for VTE >= 0.56. I think this version check is pointless (and outright harmful in this case, causing this bug), especially since the call is in a try-except block here too, gracefully handling if VTE doesn't yet support this feature.

(VTE supports "bold is bright" since version 0.52, and then 0.56 changed its default value.)

The two cases should probably use the same formula, either explicitly checking for VTE >= 0.52 (and not 0.56), or a try-except (or both, but it's pointless). Additionally, it might make sense to hide the UI checkbox for older VTEs.

**Comment by henrythebuilder** [comment]
Thanks,
for now as workaround I made explicitly checking for VTE >= 0.52 in `terminal.py` 

Thanks again for the support :+1:

**Comment by Davidy22** [comment]
Workaround found and the upstream VTE project is moving to remove the bold-is-bright option, so closing this in advent of the eventual rug pull from upstream.
