### ISSUE TITLE
Can't triple-click vim

### ISSUE THREAD

**Issue by SoniEx2** [Guake/guake#1627]
Be sure to check the existing issues (both open and closed!), and make sure you are running the latest version of Guake.

For how to run the latest Guake in your computer, please refer to [Install from source](https://guake.readthedocs.io/en/latest/user/installing.html#install-from-source).

**Describe the bug**

Guake doesn't properly handle mouse mode and spawns a new window even if mouse mode is enabled. As such it's impossible to triple-click vim to enter line-wise selection mode.

**Expected behavior**

Guake should detect mouse mode and disable all mouse handling.

**Actual behavior**

What you actually get.

Guake spawns new tab when trying to triple-click vim.

**To Reproduce**

Provide the steps to reproduce the behavior

1. Start guake
2. Start vim
3. Enable mouse mode
4. Try to triple-click to select content by lines.

-------------------------------------------------------------------------------

Please run `$ guake --support`, and paste the results here. Don't put backticks (`` ` ``) around it! The output already contains Markdown formatting. And make sure you run the command **OUTSIDE** the Guake.

<details><summary>$ guake --support</summary>

Guake Version:          3.6.3

Vte Version:            0.56.3

Vte Runtime Version:    0.56.3

--------------------------------------------------
GTK+ Version:           3.24.10

GDK Backend:            GdkX11.X11Display

--------------------------------------------------
Desktop Session: None

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  DVI-I-1
    * Geometry:         1920 x 1080 at 0, 0
    * Size:             477 x 268 mm²
    * Primary:          True
    * Refresh rate:     60.00 Hz
    * Subpixel layout:  horizontal-rgb

**Comment by RuRo** [comment]
I am having the same problem with `tmux` and double clicks.

For whatever reason, double-clicking in `tmux` opens a new Guake tab.
This does not happen, when `tmux` is closed or if the mouse mode is disabled in `tmux`.

#### To Reporduce

1. Start guake
2. Start `tmux`
3. Press Ctrl+B and type `:set-option -g mouse on`
4. Double-click to try to select a word.

This is a really weird behavior, because "open a new Guake tab" is not caused by either tmux or guake alone, but somehow the conflicting handling of the mouse results in a new Guake tab.

<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.56.3

Vte Runtime Version:	0.56.3

--------------------------------------------------
GTK+ Version:		3.24.10

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: /usr/share/xsessions/plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 -  eDP-1-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		382 x 215 mm²
    * Primary:		True
    * Refresh rate:	119.94 Hz
    * Subpixel layout:	unknown

**Comment by meridius** [comment]
I think this issue relates to #1697 because I get new tab opened no matter if I have `tmux` or `htop` opened.
