### ISSUE TITLE
Support of short term focus loss and avoid folding

### ISSUE THREAD

**Issue by katoquro** [Guake/guake#1643]
Hello! 

I had an issue with keyboard shortcuts and "Hide on lose focus" option. I'm using https://github.com/autokey/autokey and it always takes focus for very short period of time and then returns it back. 
I've tried to implement a feature when there is a timeout for the window hiding and focus is checked after timeout. I'm not good at Guake technology stack so I decided make a proof of concept and see how it works. I'm using it for several months and didn't found any major issues. 

The code can be found here 
 https://github.com/katoquro/guake/commit/87dcdbb7c6cd5d9f3376c50a7524471725d3a635 
or the last commit at this branch https://github.com/katoquro/guake/commits/feature/short-term-focus-loss
I can create a pull request if some one knows how to pull this feature as flag into the settings 

Looks like this feature can close these issues 
https://github.com/Guake/guake/issues/937 
https://github.com/Guake/guake/issues/687

**Comment by Davidy22** [comment]
You can create a pull request from your fork and we can take a look and help with getting it polished off for inclusion.

#1831 might be related too.

**Comment by Davidy22** [comment]
Alright, I've checked out and rebased your code and I can notice the small delay, but I haven't been able to observe whether or not this actually fixes the issue because my IME didn't steal focus in the first place, and I can't find a program that only swipes focus for a small moment. For adding items to preferences, I have some [open pull requests](https://github.com/Guake/guake/pull/1874) that [demonstrate adding an item to preferences](https://github.com/Guake/guake/pull/1873) that you can follow a similar path for.

**Comment by Davidy22** [comment]
Update after using this patch for a while, I realised that workspace switch also counts as a short focus grabbing event and while it was novel, I don't want guake to stick around when I switch workspaces. This may need functional reworking, also potentially this bug should be the responsibility of the IME developer since some IMEs (like mine, fcitx) are apparently able to function without taking focus and dropping you out of guake.

**Comment by katoquro** [comment]
I've rebased and pushed my PoC to create PR. 
@Davidy22 Could you explain a bit more about the behavior with workspaces? You mean guake terminal keep open in the new workspace after the switch but you want get it closed?

**Comment by Davidy22** [comment]
So, the option that's we're talking about here is the "Hide if lose focus" option. Ostensibly, people turn this on if they want guake to go away when they tab away to another program. Switching workspaces is basically tabbing away to another program, but the approach this patch takes stops guake from dismissing when we switch spaces. Ideally we want to do this in a way that still lets the temporary context switch when changing workspaces hide guake, but not an IME. Also as I noted before, not every IME seems to swipe focus and doing so might just be considerable as a bug on part of the IME.

**Comment by katoquro** [comment]
"Hide if lose focus" it's current behavior and patch supposes that there should be one more (if the first is enabled) checkbox - "Ignore short focus loss" and number field (lets say in ms) for duration of "short loss" (plesesee this line https://github.com/Guake/guake/pull/1892/commits/e28c0d892274e89016c4871f2fc234d777e8779f#diff-be8a9fc8fe311afaa1cf2a8b932b3b371cd3ad3208c5dc0f2dd4695239d52bacR509). But if after the workspace switch the focus returns to the Guage automatically this property won't help. Kind of possible workaround ¯\_(ツ)_/¯

**Comment by Davidy22** [comment]
Well if we're going to use a setting, it probably should be false by default so that the people who don't use certain IMEs aren't suddenly affected by a strange behavior change. I also notice that there isn't a setting, it's just always on by default right now. You can follow what I did in the pull requests I linked to create a new setting. You can use glade for easier editing of the UI file.

**Comment by Davidy22** [comment]
PR merged, closing.
