### ISSUE TITLE
"make uninstall" doesn't clean up

### ISSUE THREAD

**Issue by egmontkob** [Guake/guake#1646]
`sudo make uninstall` reports the following:

```
rm -f "/usr/local/share/applications/guake.desktop"
rm -f "/usr/local/share/applications/guake-prefs.desktop"
rm -f "/usr/local/share/metainfo/guake.appdata.xml"
rm -fr "/usr/local/share/guake/pixmaps"
rm -fr "/usr/local/share/guake"
rm -f "/usr/local/share/glib-2.0/schemas/org.guake.gschema.xml"
```

First, this list is incompete, it at least removes `/usr/local/bin/guake` which it doesn't report.

Second, more importantly, it leaves tons of installed stuff under `/usr/local`, including `/usr/local/bin/guake-toggle`, `/usr/local/lib/python3.7/dist-packages/guake-3.6.4.dev19-py3.7.egg-info`, `/usr/local/lib/python3.7/dist-packages/guake`, `/usr/local/share/locale/*/LC_MESSAGES/guake.mo`.

As a result, after a manual installation and uninstallation from git, followed by a reinstall of the package provided my distribution (Ubuntu 19.10 beta) I still don't get a usable Guake due to a mixture of two installations (the distro-shipped version tries to load some of the files from `/usr/local`).

Expected behavior: `sudo make uninstall` should remove everything that `sudo make install` installed. Moreover, report everything or nothing (preferably everything) during the process.

**Comment by ulidtko** [comment]
Well, fair point. I'd reported issues just like this myself.

The bitter truth is: you have to rely on your system package manager, and just keep /usr/local *empty*. The best `make uninstall` is `rm -rf /usr/local/*`. The more permanent stuff you keep alive under `/usr/local`, the more PITA you'll have with it in the long run. (However, /usr/local shines in playground-style experiments.)

Worse; **you can't trust** package authors to do uninstall properly. That is another reason why package managers exist; so that we have [this epic bug][bumblebee-gold] occur exactly once, and learn from the lesson. In that bug, an author rolled his own uninstall script, and made a fatal typo `rm -rf /usr /lib/nvidia-current/xorg/xorg` -- spot the extra space.

Sure, we'll fix this in Guake. But many more other projects won't. Many projects don't even offer `make uninstall` -- correctly delegating that function to package managers. I'm sorry that you had to have the adventure to figure this out, but the advice is: just don't make the habit to rely on it.

[bumblebee-gold]: https://github.com/MrMEEE/bumblebee-Old-and-abbandoned/commit/a047be85247755cdbe0acce6#diff-3fbb47e318cd8802bd325e7da9aaabe8L351

**Comment by egmontkob** [comment]
Thanks, I'm fully aware of all the issues you raise, I even saw the bumblebee bug back then. You can't blindly trust a `make uninstall`, just like you can't blindly trust a `make install` or any other step of the building process, nor running the app itself either, without thorougly investigating it. There can be bugs like this, as well as – accidental, or worst case, even intentional – malicious behavior.

Let's also note that there exist build systems (e.g. automake, cmake, meson) that generate the rules for you, which significantly decreases the change of something getting forgotten. You might even consider switching to one of these, although I'm not asking for that here.
