### ISSUE TITLE
Double click on mouse application opens new tab

### ISSUE THREAD

**Issue by dianlujitao** [Guake/guake#1697]
**Describe the bug**

When double clicking on applications with mouse support (htop, vim with `set mouse=a`, etc.) a new guake tab is opened, as if double clicking on the tab bar.

**Expected behavior**

No new tabs are launched.

**Actual behavior**

New tab launched every time.

**To Reproduce**

run htop
double click

-------------------------------------------------------------------------------

```
<details><summary>$ guake --support</summary>

Guake Version:		3.6.3

Vte Version:		0.58.3

Vte Runtime Version:	0.58.3

--------------------------------------------------
GTK+ Version:		3.24.13

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: /usr/share/xsessions/plasma

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - DEL DisplayPort-0
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		527 x 296 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	horizontal-rgb
* Monitor: 1 - AOC HDMI-1-1
    * Geometry:		1920 x 1080 at 1920, 0
    * Size:		527 x 296 mm²
    * Primary:		False
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown
```

**Comment by bastien-wink** [comment]
I am having the same issue on tmux with guake. Even without htop opened it start a new guake on double click

**Comment by Nikolay-Chumerin** [comment]
Have the same issue. Quite annoying.

**Comment by bastien-wink** [comment]
Not sure what trigger the "new guake window", but disabling the "set mouse on" in the tmux config file fix the issue.

We need the mouse support on guake (and vim), but it seem to create a conflict with guake click handler.
The same tmux config on other terminal emulators is working fine. I have to pause using guake after all those years of love. Looking forward to see a fix.

**Comment by Nikolay-Chumerin** [comment]
It's a bit strange bug/feature. I have it in combination of `guake` + `micro` (nice console text editor). The double-mouse-click in pure `guake` (not inside `micro`) works as expected. But this is not an issue of `micro` neither: double click in `micro` in other consoles (_e.g._, `terminator`, `gnome-terminal`, _etc_.) works properly.

**Comment by RuRo** [comment]
@gsemet I think, I know, what the problem is. It [this line in `notebook.py`](https://github.com/Guake/guake/blob/master/guake/notebook.py#L118).

Removing these lines makes it so that the new tab is not opened. Although with this "fix" the lines don't get selected when double-clicking in `tmux`/`vim` like they do in normal shell unless you hold SHIFT, but I am assuming, that this is the correct behaviour because the double click (without SHIFT) is handled by the CLI application.

It's not obvious to me, why the double click opens a new tab only when some CLI app is also trying to capture the mouse input (`tmux`/`vim`/`micro`). In fact, looking at these lines in the code, I would expect double-clicking the terminal to *always* open a new tab.

The related lines were added in commit b55e50773fdfc64baa1850031f45d56517b0a354 and it seems, that it was supposed to only open new tabs when double-clicking on the *tab bar* and not the actual terminal screen, so just removing them might be undesirable, since that would also remove this feature. Although I don't know, how widely used it is, given that there is both a `+` button as well as a hotkey combination for opening new tabs. We could also make this an option in the configs.

Any ideas about why opening `tmux`/`vim` makes Guake think that the whole terminal screen is the tab bar? Also, what is your preference for "remove double-click feature" vs "add config option".

**Comment by bastien-wink** [comment]
To me a double-click on the _tab bar_ to open a new tab isn't straight forward for a user, does anyone here use it ?
My preference is to remove that feature, adding it in the config does not seem necessary.

**Comment by gsemet** [comment]
I do not want to clutter the pref window, for me this feature is not mandatory. If we can get double click on tab bar to open a new tab that could be enough. But if we can’t get it to work without conflict with in-Terminal click we can remove this feature

**Comment by zegkljan** [comment]
If there was no other way to open a new tab, I'd be for fixing this but since this is not the case, I say remove this feature now and maybe reintroduce it when it works properly.

**Comment by gsemet** [comment]
You can still right click on a tab or click on the "+" button. The "Double-click opens a tab" is a nice feature, but not mandatory. Remove it, explaining why it has been done, and we will reintroduce it if needed later (probably by putting a stretched widget in the tab bar somehow that will receive the double-click event, instead of the notebook. But usage within the terminal is more important

**Comment by paulkitt** [comment]
Still facing this problem running nvim 0.4.4/ vim 8.2 with guake 3.7.0-1 on Arch Linux. Anybody any guess why?

**Comment by harshavardhanc** [comment]
+1 @paulkitt, I'm also facing same issue with 3.7 guake, nvim 0.4.3 on arch linux.

**Comment by laurentlbm** [comment]
The problem is still there because there hasn't been any new release since the bug was fixed.

**Comment by gsemet** [comment]
Indeed, I got a bit lost with guake maintainance lately. I have merged a couple of PR, I would be glad if some of you can retest it to see if everything still works fine (I do not have an environment to test it, macos only now...).

Once it is ok, I can do a new release

**Comment by bingguo1** [comment]
totally agree, please "add an option to `enable/disable double click open new tab` in `Guake preferences`" as in
https://feathub.com/Guake/guake/+73

**Comment by paulkitt** [comment]
Is this repository dead? Maybe its time to archive the project or hand it over to a new maintainer.

**Comment by gsemet** [comment]
hi. Are you a volunteer?

**Comment by paulkitt** [comment]
Hi! No I am an user since a long time and curious about the state of the project. I am not experienced in python enough for such a big application to debug. Dont get me wrong I dont say do anything. From your last comment I just had the impression that the project is not maintained anymore. No problem with that its just good to know if so. Thanks for your work! Guake Terminal is/was a great help for me and a lot of my friends.

**Comment by bastien-wink** [comment]
This issue have been closed, you should create a new one. 
The project still have active development : https://github.com/Guake/guake/pulse/monthly

**Comment by gsemet** [comment]
no pbl. I indeed struggle at this maintainance, but I gladly welcome pull requests :)
