### ISSUE TITLE
LinuxMint's repo (I'm guessing its Ubuntu's ones) still installs version 3.6.3 instead of the latest

### ISSUE THREAD

**Issue by catalin560** [Guake/guake#1803]
How can I get the latest besides painfully compiling from source?

**Comment by eaghion** [comment]
You could do the following (I tested on Linux Mint 19.3 (base: Ubuntu 18.04) Tricia Cinnamon 64Bit):

`sudo add-apt-repository ppa:linuxuprising/guake` 
`sudo apt-get update`
`sudo apt install guake`

Output of `guake --version`:

Guake Terminal: 3.7.0
VTE: 0.52.2
VTE runtime: 0.52.2
Gtk: 3.22.30

I did this because since I'm on Linux Mint 19.3 I was stuck on guake version 3.0.5, which is quite old and lacks certain features, like the split view, etc.

You may need to kill the guake process (System Monitor is fine) and start it again (you can do this from the menu/GUI).

Hope this helps!
