### ISSUE TITLE
impossible change position of guake

### ISSUE THREAD

**Issue by backl1n** [Guake/guake#1864]
im on ubuntu 20.04 with gnome its impossible to change position of windows

**Comment by dxps** [comment]
Press the `meta` key (Win/Super or Alt, depending on your setting) and:
- left click you should be able to drag the window
- right click you should be able to resize the window

But it looks like that after a hide & show (toggle by default using F12), it gets back to the original/default size.

Therefore, you'd need to use such preferences to set up a position.Here is what I have in my case:
![image](https://user-images.githubusercontent.com/14140226/126876634-09383e0d-ce6c-4f13-aa69-4882441c5624.png)


Note: I just installed it and started playing with it since I love the fact that it can save the session, so that next time starting it I would get the last state of tabs and places.

Hope it helps.

**Comment by backl1n** [comment]
jai toujours la position qui reviens par default

**Comment by Davidy22** [comment]
Alt-dragging the guake window will not save the position of the guake window and will return to the original position when you reopen. Does the position not save for you when you use the displacement modifiers circled red in the image above?
