### ISSUE TITLE
Pressing a any general shortcut triggers the "toggle on lose focus" option

### ISSUE THREAD

**Issue by lgarczyn** [Guake/guake#1923]
**Describe the bug**

I'm trying to have both a general keyboard shortcut to toggle guake, let's say `ctrl + space` and the 'toggle on lose focus' option on.

If I press `ctrl + space` in guake, nothing happens, but if I have `ctrl + space' set to anything in the ubuntu shortcut settings, guake loses focus. 

If `ctrl + space` is set to `guake -t` as in the example, guake will close and reopen instantly after, defeating the purpose of `guake -t`.

This makes it impossible to set a guake toggle in a general shortcut.

**Expected behavior**

I would not expect general ubuntu shortcuts to systematically steal focus from the active window

**Actual behavior**

Guake closes. If the command is to toggle guake, then guake toggles on again.

**Workaround**

One solution is to use the guake shortcuts instead, but this limits you to the keys that ubuntu allows as shortcuts. No caps lock, `ctrl+tab`, etc.

Another solution would be to implement `guake --is-open` to allow the shortcut command to verify the current state.

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.7.0

Vte Version:		0.60.3

Vte Runtime Version:	0.60.3

--------------------------------------------------
GTK+ Version:		3.24.20

GDK Backend:		GdkX11.X11Display

--------------------------------------------------
Desktop Session: gnome

--------------------------------------------------
Display: :1

RGBA visual: True

Composited: True

* Monitor: 0 - BOE eDP-1-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		309 x 174 mm²
    * Primary:		True
    * Refresh rate:	60.00 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
So, the semantics are a little weird here because presumably this is supposed to resolve an issue with focus being yoinked by keyboard shortcuts outside of guake while toggle on lose focus is on. Creating a new flag for checking if Guake is open or not doesn't actually do anything, because by the time we get to running the Guake command bound to the keyboard shortcut, we've already hidden the Guake window. Guake already detects whether or not it is open when deciding what to do when you hit the show/hide key.
