### ISSUE TITLE
Tabs bar is hardly visible (background-opacity ?)

### ISSUE THREAD

**Issue by cmalard** [Guake/guake#1981]
**Describe the bug**

Tabs bar is hardly visible (background-opacity ?)
(white page opened in my browser behind)
![image](https://user-images.githubusercontent.com/1692136/143311695-ee5b3c9e-7447-4fc7-9b7c-d0c97df31abd.png)
(picture behind)
![image](https://user-images.githubusercontent.com/1692136/143311624-7e1f49a8-8259-4ab8-b1ea-a30e3d82586e.png)

**Expected behavior**

The background of the tabs bar should be the same as tab content.

**Actual behavior**

Background-opacity = 0 I guess

**To Reproduce**

Open Guake and have tab bar visible.
I tried all options to see if it has an impact, it doesn't. Even if tabs are placed on top.
![image](https://user-images.githubusercontent.com/1692136/143311986-40ae6b70-6746-4524-9634-9819e114ac97.png)

-------------------------------------------------------------------------------

<details><summary>$ guake --support</summary>

Guake Version:		3.8.1

Vte Version:		0.64.2

Vte Runtime Version:	0.64.2

--------------------------------------------------
GTK+ Version:		3.24.30

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: ubuntu-xorg

--------------------------------------------------
Display: :0

RGBA visual: True

Composited: True

* Monitor: 0 - SDC eDP-1
    * Geometry:		1920 x 1080 at 0, 1080
    * Size:		344 x 194 mm²
    * Primary:		True
    * Refresh rate:	59.962 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - IVM HDMI-1
    * Geometry:		1920 x 1080 at 0, 0
    * Size:		544 x 303 mm²
    * Primary:		False
    * Refresh rate:	60.0 Hz
    * Subpixel layout:	unknown

**Comment by Davidy22** [comment]
Are you using the Yaru theme? We've had some reports of issues with that theme before, and upstream has put in fixes that will trickle down. The core of this issue is the guake used to not actually use the system theme, and now it does, and yaru and some other themes have the tab bar set to transparent and our layout doesn't have anything behind the tab bar so it just looks see-through. For now if you go into preferences and uncheck "use system default theme," and pick a theme out, it should look like it did before.

**Comment by cmalard** [comment]
Yep! :-D With the theme Adwaita-dark, I don't have the issue, same with the uncheck of system default theme :+1:


I let you reopen if you need to keep this issue for tracking, thanks for the quick answer and the help :beers:
