### ISSUE TITLE
VTE Title not always working

### ISSUE THREAD

**Issue by db4rne** [Guake/guake#203]
The automatic tab renaming isn't always working, especially not if you use some colours in your hostname. It would be nice if this could be fixed, since the feature is really cool.

**Comment by Senset** [comment]
Hi, I had the same issue, but difference on:
if other server hostname contains dots - VTE does not rename a tab

**Comment by mlouielu** [comment]
@Senset Could you [run with latest version guake](http://guake.readthedocs.io/en/latest/user/installing.html#install-from-source) and give us the result of `guake --support`?

**Comment by ulidtko** [comment]
@Senset please try this quick test:

    $ printf '\x1b]0;asdf@qwer.zxcv\a'; sleep 2

 + **If you do see** the tab title change to `asdf@qwer.zxcv` for 2 seconds -- then Guake works just fine. It certainly does for me; so, can't confirm this as guake bug.
 + **If you don't see it** -- then it's a Guake/libvte bug.

Most likely, it's your shell setup (bashrc/bashprofile/zshrc what have you) that fails to process the dots in FQDN correctly. Oh! and make sure you use **`\H`** instead of `\h` in your PS1. `man bash` <kbd>/^PROMPTING</kbd> for more info.

**Comment by Senset** [comment]
@ulidtko 
Yeap =( I see "asdf@qwer.zxcv". Sorry, thx
