### ISSUE TITLE
Pip installation is broken on FreeBSD 13.0

### ISSUE THREAD

**Issue by Xevib** [Guake/guake#2052]
**Describe the bug**

The installation of guake through pip fails on FreeBSD 13.0 and Python3.8.12

**Expected behavior**

Work out of box

**Actual behavior**

When I try to run guake I get this error:
![image](https://user-images.githubusercontent.com/2422305/156913934-4b152d39-aabd-4522-a092-132f9a008185.png)

I bypassed the error copying the data folder from github to  the expected location but this can be a problem for other users

**To Reproduce**

Just ``` pip install guake```

**Comment by Davidy22** [comment]
Guake has some dependencies that pip doesn't install, which makes the pip installation not as ideal for the first installation of Guake. Pip would be more for getting the latest version once you've installed from package manager once before. Just to check, what happens when you run `glib-compile-schemas -h`? From the error message it looks like that might be missing.

**Comment by Xevib** [comment]
@Davidy22  do you need more information? or with this screenshoot is enougth?

**Comment by Davidy22** [comment]
The screenshot tells me that `glib-compile-schemas` is indeed present, so that was my main idea of where the source of the issue may be out. Only other ideas include checking what's inside that directory indicated with the long path and manually entering the full `glib-compile-schemas` command that the last line was trying to run to see the output.

**Comment by Xevib** [comment]
I executed:
glib-compile-schemas --strict /home/xevi/.local/lib/python3.8/site-packages/guake/data

And I get:
S'ha produït un error en obrir el directori «/home/xevi/.local/lib/python3.8/site-packages/guake/data»: No such file or directory

If I do "ls  /home/xevi/.local/lib/python3.8/site-packages/guake/" this is the output:
__init__.py       about.py          common.py         dialogs.py        guake_app.py      keybindings.py    notebook.py       paths.py          simplegladeapp.py terminal.py
__pycache__       boxes.py          customcommands.py globals.py        guake_logging.py  main.py           notifier.py       prefs.py          split_utils.py    theme.py
_version.py       callbacks.py      dbusiface.py      gsettings.py      guake_toggle.py   menus.py          palettes.py       settings.py       support.py        utils.py

**Comment by Davidy22** [comment]
That would be the python install dir, which means guake is going to the pure pip one primarily and that's messing up somehow. Try fully uninstalling from pip, installing the regular repo version, then installing the pip version and try that

**Comment by Davidy22** [comment]
Pushed a commit that might resolve this, you can try the wheel in the dist [here](https://github.com/Guake/guake/actions/runs/2509811717) or see the next release
