### ISSUE TITLE
Unusable on Ubuntu 22.04

### ISSUE THREAD

**Issue by MattSom** [Guake/guake#2186]
Just leaving this here. Installed it an hour ago and just found like the 6th issue/bug that worked fine on 20.04 but functions not on 22.04. Found most of them as open issue here, they are at least a year old. 
Is this like abandonware at this point?

**Comment by Davidy22** [comment]
Closing because this doesn't describe a bug or feature request, there's a discussion tab for general discussion. `guake --support` output would aid in figuring out what's happening, the guake version should be more pertinent than the ubuntu version number, particularly because the pinned version of guake in the ubuntu 22.04 repo is almost two years old and you likely won't see any of what has been fixed since then unless you use the PPA.
