### ISSUE TITLE
Trailing whitespace inclusion/exclusion in clipboard copies from Guake

### ISSUE THREAD

**Issue by JesseCoretta** [Guake/guake#2268]
I'd like to propose a new feature that could reduce pain points for some users. It relates to the clipboard copying of selected text **from** Guake that contains line-ending whitespace. The urgency is fairly low, even though it is frustrating to me personally.

When **copying** selected text content **from** the Guake terminal by way of "triple-clicking" or "select-all", trailing (line-ending) whitespace is subsequently copied needlessly. This issue is visible when pasting **into** any other app that can receive text input -- such as GVim or another terminal app -- and causes issues for any application or process which does not automatically mitigate the issue on its own through trailing whitespace truncation.

To mitigate this issue on my own, I've added a custom vim function which simply runs `%s/\s\+$//g`. The only problem is that one has to _remember_ to execute this function, and for reasons I won't go into, its not ideal to run automatically (as triggered by `:w` or when run at automated intervals).

I don't want to speak for everyone, so to avoid suggesting something that may introduce breaking changes, the resolution to this issue may be better served through a _configurable_ option, which could theoretically instruct Guake as to whether selected line-ending whitespace should be included during the copy process. In my own personal case, such removal is **always desirable**. I'll leave it to the devs to decide what the default state for such an option should be (true vs. false).

To offer a real-life example of what I mean, consider GVim's behavior when **copying** selected text (via triple-click or select all) and pasting it elsewhere. GVim does not introduce trailing whitespace during the copy process (unless that whitespace is already present). I realize GVim is a _text editor_ and not a terminal, but its still a valid example IMO.

Feel free to chime in with comments, concerns or questions.

<details><summary>$ guake --support</summary>

Guake Version:		3.10

Vte Version:		0.68.0

Vte Runtime Version:	0.68.0

--------------------------------------------------
GTK+ Version:		3.24.33

GDK Backend:		<GdkX11.X11Display

--------------------------------------------------
Desktop Session: xfce

--------------------------------------------------
Display: :0.0

RGBA visual: True

Composited: True

* Monitor: 0 - BNQ HDMI-1
    * Geometry:		2560 x 1080 at 0, 0
    * Size:		820 x 346 mm²
    * Primary:		True
    * Refresh rate:	59.978 Hz
    * Subpixel layout:	unknown
* Monitor: 1 - LGD eDP-1
    * Geometry:		1920 x 1080 at 2560, 0
    * Size:		309 x 174 mm²
    * Primary:		False
    * Refresh rate:	60.02 Hz
    * Subpixel layout:	unknown

**Comment by egmontkob** [comment]
VTE developer chiming in. (VTE is the terminal emulation widget of Guake and many others, and is the component responsible for copy-pasting, although Guake could override it I guess if it wanted to.)

VTE copies a trailing space if and only if there was a space character printed at the end of the line, rather than "empty" a.k.a. "erased" cells which are there by default and can also appear there as the result of various erasing escape sequences.

I'm a bit puzzled by this statement, the part in parenthesis:

> GVim does not introduce trailing whitespace during the copy process (unless that whitespace is already present).

because as I'm testing, this is exactly the behavior I get in a `vim` running inside Guake: you don't get trailing whitespace unless it's part of the file.

Is it not what happens to you, too? Maybe it depends on Vim's config, Vim's version or build options, faulty `$TERM` value, running it under Screen/Tmux, etc.

In particular, this certainly happens if Vim with a non-default background color is running under Screen/Tmux. This is a limitation of the capabilities of the terminal type that Screen/Tmux provide towards the application that they host (i.e. Vim). Their terminal type doesn't support `bce` ("background color erase"), meaning that it can't produce a cell in the "erased" state that also has a nondefault background color, the only choice for an application to have those cells painted with some background color is to explicitly paint a space character there, which thus becomes a copy-pasteable space in VTE. Is this the setup you have: Screen/Tmux, and Vim with a custom background color?

Maybe it's something that's better followed up by Script/Tmux and Vim developers. As for VTE and many other terminals, Vim (without any intermediately layer in between) does have control over which trailing spaces are to be copied (literally ASCII "space" characters) and which aren't (empty cells), and Vim seems to use this power correctly.

That being said, Guake/VTE _could_ have an option to strip trailing spaces, I'm just not entirely sure if it really _should_ have it (e.g. does GVim have such an option, i.e. to strip trailing spaces even if explicitly part of the text file?). Not being able to preserve explicit whitespaces isn't a direction that I'm happy about, as in some file formats (e.g. Markdown) they do make a difference.

So what is _exactly_ your request? To strip _all_ trailing spaces, even if they are explicitly there in the file? (Can you do that in GVim and other popular editors? Also: what to do if you select a part of a line, e.g. a line contains "lorem ipsum" and you visually select "lorem " (with that trailing space), should that space be preserved or dropped?) Or to strip trailing spaces only if they're not part of the file? (This is what Vim in Guake does for my by default, it should work unless you combine Vim with Screen/Tmux, in which case I think the problem is better addressed over there.)

**Comment by JesseCoretta** [comment]
Hi! @egmontkob 

> I'm a bit puzzled by this statement, the part in parenthesis:
> 
> > GVim does not introduce trailing whitespace during the copy process (unless that whitespace is already present).
> 
> because as I'm testing, this is exactly the behavior I get in a `vim` running inside Guake: you don't get trailing whitespace unless it's part of the file.

Whether I am just at my shell, or in vim, the entire width of the terminal is copied in terms of spaces, even if not present.

Observe:

```
$ vi test
i <editor mode>
this is a test<I hit ESC, which exits edit mode>
<Triple click to select text, which has no trailing space whatsoever>
<Enter another quake session>
Paste <Note I've put quotes "..." around the white space which was pasted to my terminal so you can see it>

jesse@localhost:~$ <PASTE HERE>this is a test"                                                          

" <-- whitespace ends here.
```

But I mentioned GVim (not terminal vim, but rather the GUI app), just because it was a common use case that easily demonstrates the contrary of the above behavior:

```
<Open GVim>
i <editor mode>
this is a test<ESC>
<Triple click to select (note I can see the highlighting is limited to the value only)>
<Enter another quake session>
Paste

jesse:~$ this is a test <-- ends here, no whitespace
```

> 
> Is it not what happens to you, too? Maybe it depends on Vim's config, Vim's version or build options, faulty `$TERM` value, running it under Screen/Tmux, etc.

See above, although that's a good point. I guess what I was really getting at was that any copying I do in Guake seems to have "overzealous" effects. But then again, maybe its simply overzealous "_selecting_".  I'm not too familiar with the internals of Guake in that regard.

> 
> In particular, all trailing blank is unexpectedly copied if Vim with a non-default background color is running under Screen/Tmux. This is a limitation of the capabilities of the terminal type that Screen/Tmux provide towards the application that they host (i.e. Vim). Their terminal type doesn't support `bce` ("background color erase"), meaning that it can't produce a cell in the "erased" state that also has a nondefault background color, the only choice for an application to have those cells painted with some background color is to explicitly paint a space character there, which thus becomes a copy-pasteable space in VTE. Is this the setup you have: Screen/Tmux, and Vim with a custom background color?

I think the answer to your question is no. I'm not using screen as my physical machine is Linux and do not terminal-in from other locations.

But here is my `.vimrc` -- note that both `vim` **and** GVim use this **same** config:

```
set printoptions+=formfeed:y                                            "
set printoptions+=header:0                                              "
set colorcolumn=72                                                      "
set vb                                                                  "
set t_vb=                                                               "
set spellfile=~/.vim/spell/en.utf-8.add                                 "
set mmp=5000                                                            "
map <C-j> 58j                                                           "
map <C-K> :%s/\s\+$//g<CR> 
```
The last line is the "fix" I mentioned when I opened this issue, FWIW.

NOTE: I left trailing whitespace in this example for your review. The above was acquired through a mouse drag select from `vim` in Guake.  I've terminated the actual line endings for visibility, but note the LAST line does not have any trailing whitespace because (again) it was a drag select that stopped at that point.

> 
> Maybe it's something that's better followed up by Script/Tmux and Vim developers. As for VTE and many other terminals, Vim (without any intermediately layer in between) does have control over which trailing spaces are to be copied (literally ASCII "space" characters) and which aren't (empty cells), and Vim seems to use this power correctly.

I understand. But keep in mind, this issue occurs even without vim (e.g.: copying the contents of my terminal -- specifically my visible bash history -- for tutorials I write,  which I frequently do).   So its definitely nothing to do with the specific applications which are executed in Guake ... or, at least that's how it seems to _me_.

> So what is _exactly_ your request? To strip _all_ trailing spaces, even if they are explicitly there in the file? (Can you do that in GVim and other popular editors? Also: what to do if you select a part of a line, e.g. a line contains "lorem ipsum" and you visually select "lorem " (with that trailing space), should that space be preserved or dropped?) Or to strip trailing spaces only if they're not part of the file? (This is what Vim in Guake does for my by default, it should work unless you combine Vim with Screen/Tmux, in which case I think the problem is better addressed over there.)

Let me hold off on answering that until you see the information I've provided. Not sure if it will change the direction of this discussion, so rather than hit you with a wall of text needlessly, I'll wait to see your next reply 😃 

Thank you!

**Comment by egmontkob** [comment]
Your `vim` configuration asks to have a red marign at column 72. The way `vim` can achieve this layout is to fill up the area with spaces up to that point.

In VTE (and a few other terminals) `vim` could move the cursor to column 72, switch to red background, erase to the end of the line; then move to column 73, switch to the default background, and again erase to the end of the line. In that case you'd have that red margin cell there but it wouldn't be part of copy-pasting. I don't think however that this behavior is "standard" by any means and that copy-pasting would skip that cell in every popular terminal. (Also it has a tiny-tiny-tiny chance of the entire remaining line flashing up with red for a brief moment.) Therefore I'm not surprised at all that Vim doesn't do this.

Does the copied buffer contain _more_ than this amount of whitespace? What if you remove this part of your Vim config, or start from scratch with an empty config? Also could you please show another example where Vim is not involved?

As for pasting, the text "screenshot" that you provided

> ```
> jesse:~$ <PASTE HERE>this is a test"                                                          
> 
> " <-- whitespace ends here.
> ```

doesn't tell much, the Markdown source shows lots of trailing spaces in the first line but the rendered version doesn't, also unclear why the second line is empty -- does the buffer end in two newline characters rather than one? I can't tell.

Copy-pasting the Markdown source into a text editor, I get contents that fill up exactly 72 columns (the text plus the spaces, minus the `"` sign you inserted), which corresponds exactly to the margin you set up in Vim. Still unclear to me though why you have an additional newline character (two instead of one).

So far what we're seeing is that Vim explicitly prints that many space characters, and therefore VTE includes them in the clipboard.

**Comment by egmontkob** [comment]
> could move the cursor to column 72, switch to red background, erase to the end of the line; then move to column 73, switch to the default background, and again erase to the end of the line

Another possibility _could_ be to move to column 72, switch to red background, and use the escape sequence ICH which inserts one character, pushing the rest to the right.

This eliminates the tiny-tiny-tiny chance of the entire remaining row flashing up in red.

It works in VTE as in: the newly introduced cell is an "erased" one, the previous ones also remain so, therefore copy-pasting works as you'd expect. However, Xterm inserts a space, and all the preceding erased cells now behave wrt. copy-pasting as if they were spaces. You see, we're entering the territory where terminal emulators behave differently.

(You might be interested in juicy details at VTE issues 2663, 2676, and probably a few other linked ones where the discussion between `j4_james`  and me revealed that the desired exact behavior is unclear from the available ancient pieces of documentation and actual hardware terminals (which of course didn't even have copy-pasting), they're all different and all inconsistent and contradicting in their own ways. We can't promise either that VTE won't change its behavior at one point.)

Unfortunately it's not a well-defined area in terminal emulation what should happen exactly at copy-pasting, and especially how to have non-default cells that aren't to be copy-pasted.

**Comment by JesseCoretta** [comment]
Fair enough, I'll withdraw this. Thank you for your help 😃
