### ISSUE TITLE
Ubuntu 14.04 LTS: Unable to bind global key (especially F12)

### ISSUE THREAD

**Issue by obiwanus** [Guake/guake#316]
![guake-f12](https://cloud.githubusercontent.com/assets/179863/2773662/d35cdef4-caa1-11e3-991a-97fdb67d6f95.png)

Tried the ubuntu repository version and the newest github version. The latter had the same bug but also had some other bugs such as not being able to hide by the toggle key.

Not only aren't you able to use F12, you cannot also use various other keys. Had to set Shift+F1, very annoying.

**Comment by epaminond** [comment]
Have the same issue and couldn't find a solution. (

**Comment by epaminond** [comment]
Actually just found a [workaround](http://askubuntu.com/questions/585020/set-f1-to-close-windows) with  Keyboard Settings. It worked for me after rebooting.

**Comment by airbussai** [comment]
For me it was update-alternatives that caused this error. After guake installation it changed default terminal to guake, so Ctrl+Alt+T opened it instead of gnome-terminal. I changed /etc/alternatives/x-terminal-emulator link to /usr/bin/gnome-terminal, and that solved the problem. Now Ctrl+Alt+T shows regular terminal, and F12 shows guake. So, in commands (with sudo):
'cd /etc/alternatives/'
'mv ./x-terminal-emulator ./x-terminal-emulator.bak'
'mv ./x-terminal-emulator.1.gz ./x-terminal-emulator.1.gz.bak'
'ln -s /usr/bin/gnome-terminal ./x-terminal-emulator'
'ln -s /usr/share/man/man1/gnome-terminal.1.gz ./x-terminal-emulator.1.gz'

**Comment by Crusader4Christ** [comment]
So what is the solution? Can`t use guake with this problem

**Comment by druidxz** [comment]
Hi guys! Ubuntu 14.04.5
I have just found some crutches for this issue without any additional installation.
1. Open "Keyboard" settings window and proceed to the shortcuts tab. Then select **any unassigned** shortcut and try to assign F12 to it. In the case of conflict you will be warned which command holds this shortcut. 
2. Open "Keyboard" settings window and proceed to the shortcuts tab. Then select **the same** shortcut and remove F12 key bind ( press "backspace")
3. Try to assign F12 in guake properties. If no any warnings, it worked.
4. Add "guake" to autostarts. 
![2016-09-11 14 50 20](https://cloud.githubusercontent.com/assets/22130186/18417085/57a9331e-782f-11e6-9572-c84c931b85ba.png)
And reboot machine.

**Comment by PanAeon** [comment]
Hi, I also had this problem. After I have disabled Commands plugin from the Compiz Config Settings Manager the issue has gone.
