### ISSUE TITLE
Broken tray icon with Appindicators

### ISSUE THREAD

**Issue by cl0ne** [Guake/guake#433]
Cinnamon 2.4.5 (System Tray applet), Arch Linux, libappindicator 12.10, leftmost icon is Guake:
![2015-01-01 03 07 02](https://cloud.githubusercontent.com/assets/271097/5591425/6a611cc4-9163-11e4-9fd1-c67f97abd4c1.png)

As a quick-and-dirty solution I'm using

``` patch
--- guake_app.py    2015-01-01 03:23:58.251836090 +0200
+++ guake_app.py.orig   2014-11-23 19:36:50.000000000 +0200
@@ -146,7 +146,7 @@
             self.tray_icon.connect('activate', self.show_hide)
         else:
             self.tray_icon = appindicator.Indicator(_("guake-indicator"), _("guake-tray"), appindicator.CATEGORY_OTHER)
-            self.tray_icon.set_icon(pixmapfile("guake-tray.png"))
+            self.tray_icon.set_icon("guake-tray")
             self.tray_icon.set_status(appindicator.STATUS_ACTIVE)
             menu = self.get_widget('tray-menu')
             show = gtk.MenuItem(_('Show'))
```

**Comment by RedGearPro** [comment]
Bump! Manjaro with xfce:
![image](https://cloud.githubusercontent.com/assets/8226605/6351210/91851b42-bc07-11e4-9de7-00b9c6ef5b8a.png)
Left one is guake.

**Comment by sanderboom** [comment]
MATE (GTK2):
![image](https://cloud.githubusercontent.com/assets/5956570/8008997/f37b2c04-0ba5-11e5-81b6-989d3151f446.png)
Most left is ... you guessed it

**Comment by Jesse-Millwood** [comment]
I don't know if this applies here or not but with Xubuntu 14.04 the original guake icon shows up in my Notification area but it does not use the icon for my theme. 
![selection_058](https://cloud.githubusercontent.com/assets/5342237/8678659/b4eca44e-2a23-11e5-87ad-9566f1c41966.png)

I have guake 0.7.2 on Xubuntu 14.04. For me this is just a minor annoyance. Otherwise I could not be happier with guake!

**Comment by thwarted** [comment]
Just throwing some more information out there since I'm investigating this issue right now...

Also an issue for me on Fedora 21, xfce spin, xfce4-panel-4.10.1-6.fc21 x86_64, guake 0.7.2.  It wasn't always like this, I think the package compiled by upstream that was installed on my system on July 3rd is when it started happening. From looking at the package changelog, I think this package made no local modifications.

The tool-tip "Guake Terminal" also doesn't show on my setup.  That, and poking around in the code trying various things, makes me think that this is some new incompatibility with some tray related desktop environment library (which may have also been updated around the same time).

Investigation continues...

**Comment by thwarted** [comment]
Really should have seen this sooner, it's been a long day...I was concentrating on the code in the exception handler for when `import appindicator` fails.  On July 1st I happened to pull in the package python-appindicator as part of another package's dependency resolution, and that's what broke this for me.

The (reverse) of the patch given by @cl0ne in the original issue fixes this for me.

**Comment by shirishag75** [comment]
It looks weird in mate-panel 1.20.3 

I am using ayatana appindicator but still it looks weird/broken 
![guake-looks-weird-in-mate-panel](https://user-images.githubusercontent.com/727626/46784726-d6d08b00-cd4c-11e8-9dad-d6403d823f6b.png)

I did see the png files but came none the wiser - 

```
$ dpkg -L guake | grep png
/usr/share/guake/data/pixmaps/add_tab.png
/usr/share/guake/data/pixmaps/guake-128.png
/usr/share/guake/data/pixmaps/guake-48.png
/usr/share/guake/data/pixmaps/guake-64.png
/usr/share/guake/data/pixmaps/guake-notification.png
/usr/share/guake/data/pixmaps/guake-tray.png
/usr/share/guake/data/pixmaps/guake.png
/usr/share/guake/data/pixmaps/quick-open-python-exception.png
/usr/share/guake/data/pixmaps/quick-open-selection.png
/usr/share/guake/data/pixmaps/quick-open.png
/usr/share/pixmaps/guake.png




```

**Comment by ivoshm** [comment]
Looks like more general problem. If tray icon is zoomed at 21+ px, it's broken - in my case in XFCE panel (see #1110).

**Comment by shirishag75** [comment]
There is something called Ayatana indicators which is a continuation of appindicator and they have made something called guake-indicator as well . 

Some links for more background - 

https://sunweavers.net/blog/node/67
https://lists.debian.org/debian-devel/2018/03/msg00506.html
https://ayatanaindicators.github.io/
https://wiki.debian.org/Ayatana/IndicatorsTransition
https://wiki.debian.org/Ayatana/IndicatorsTransition#Package:_guake-indicator

**Comment by gsemet** [comment]
hi. If you feel motivated to hack the guake code to make it work on your system, I would be so glad :)
