### ISSUE TITLE
Gap on the right in Ubuntu 15.04

### ISSUE THREAD

**Issue by Suor** [Guake/guake#522]
I just updated to Ubuntu 15.04, Guake 0.5 and now I have a gap on the right, although guake width is set to 100%. If I set align right the gap persists, so it's not the incorrect width bug.
![guake-gap](https://cloud.githubusercontent.com/assets/284103/7471142/a361faba-f34d-11e4-8a8f-d1d6be5b1ae5.png)

**Comment by Suor** [comment]
Updated to 0.7, and this is fixed there. Closing, sorry.

**Comment by Vizzard** [comment]
I don't believe it's fixed. I have this on Ubuntu 15.04 with Guake 0.7.2.
Changing guake-0.7.2/src/guake/guake_app.py line 871:
window_rect.width = window_rect.width - unity_dock
like this by removing "- unity_dock":
window_rect.width = window_rect.width
and running 'dev.sh --reinstall' and 'dev.sh --install' fixed issue for me.
Looks like 'window_rect.width' already has correct value because guake is full width when launcher is hidden and when launcher is visible it also has correct size (100% screen width minus launcher width). It's working even with different launcher size set (both smaller and larger than default).

**Comment by Davidy22** [comment]
Fixes merged and original submitter marked resolved, closing.
