### ISSUE TITLE
Hotkey for Grab Focus

### ISSUE THREAD

**Issue by kikecalpe** [Guake/guake#62]
Hotkey for Grab Focus http://guake.org/ticket/480
Reported by:    Nicolas     Owned by:   somebody
Priority:   minor   Milestone:  0.5.0
Component:  guake   Version:  
Keywords:       Cc:  
Description

Hi, this is a very great tool! I use it everywhere - at work, at home, in my dreams... kidding. ;-)

What I miss most is the possibility to grab the guake focus via hotkey, because guake is not in the alt+tab window switcher.

This would be a handy enchancement!

Regards, Nicolas

**Comment by wranvaud** [comment]
Just having the option "Alt+TAB" in the preferences would be awesome

**Comment by Stibbons** [comment]
I do'nt think this will be allowed by your window manager, since it is the standard hotkey for switching app...

**Comment by wranvaud** [comment]
That's exactly what I would like, switch between apps, including Guake. I've done what smasty suggested to achieve this but a checkbox in preferences would be more user friendly ;)

**Comment by MatthiasKauer** [comment]
@smasty Is that workaround still functional? 
I find a /usr/share/guake/guake.glade (instead of .glide), but it doesn't have that option on line 8. I changed the one I found further down but it didn't seem to help (after restart of guake only). Guake is nowhere to be found in Alt-tab list. This is guake 0.7.2 on debian testing with xfce 4.12.

**Comment by smasty** [comment]
@MatthiasKauer Yes, it should still work.
In 0.7.2, the line is 378, and yes, the file is `/usr/share/guake/guake.glade`, there is a typo in my original comment.

**Comment by Stibbons** [comment]
actually guake is made not to appear in alt tab and react only to our magic hotkey....

**Comment by MatthiasKauer** [comment]
@Stibbons Yes, but if guake is not set to auto-hide I cannot get back into its window without using the mouse otherwise. Are there are other options?
@smasty Thank you!

**Comment by silgon** [comment]
Got the same problem, whenever the gnome keyring is shown (let's say for a git pull or any ssh activity) guake gets out of focus and then it doesn't come back, so I have to click with the mouse or toggle hide/show twice. My nasty wayaround is a keybinding that does "xdotool click 1", because my mouse is usually in the position of the terminal. I'm using xubuntu 14.04, any news about this topic?

**Comment by felipeespic** [comment]
No news yet? Having this feature would be really useful.

**Comment by denis-gonzo** [comment]
I tried to deal with it, and here what I came to:
The reason is that **keybinder** takes away focus every time when processes the key assigned globally. Therefore, it is impossible to know whether the terminal had a focus or any other window when show_hide is executed.
I apologize for the Google Translate

**Comment by Stibbons** [comment]
Should be fixed

**Comment by felipeespic** [comment]
@gsemet
> Should be fixed

So what's the solution?

**Comment by SergiyKolesnikov** [comment]
@felipeespic In Guake Preference, under Keyboard shortcuts, in the General menu, there is an action "Show and focus Guake window". You can assign a shortcut to it (e.g. Ctrl+F12) and use it to focus a Guake window.

**Comment by V3rochka** [comment]
For Guake 3.6.3, use `/usr/share/guake/data/guake.glade`
It works!

**Comment by talengu** [comment]
> For Guake 3.6.3, use `/usr/share/guake/data/guake.glade` It works!

3.8.5 do not have /usr/share/guake/data/guake.glade and /usr/share/guake/guake.glade do not OK.
@V3rochka @smasty

**Comment by dbolser** [comment]
10 years later and still trying to get this to work... Do I need to reboot after editing the glade file?

**Comment by talengu** [comment]
> 10 years later and still trying to get this to work... Do I need to reboot after editing the glade file?

just restart guake 🐱

**Comment by fde-capu** [comment]
Enable 'Refocus if open';
Run `sudo sed -i '/GtkWindow/,/child/ { /skip_taskbar/ s/True/False/ }' /usr/share/guake/guake.glade`
Restart Guake.
