### ISSUE TITLE
guake creates zombies on gnome 3.18

### ISSUE THREAD

**Issue by rumpelsepp** [Guake/guake#636]
![screenshot from 2015-10-13 08-46-40](https://cloud.githubusercontent.com/assets/1961699/10447708/02c343da-7187-11e5-9e5f-9d7cd433c214.png)

**Comment by coderstephen** [comment]
I am experiencing this as well, and it is driving me crazy. I'm using tmux as my shell, which means zombie tmux clients pop up and mess with tmux. I don't think I can even use Guake right now because of this.

Note that for me the zombie processes only tend to show up when opening Guake about, preferences, or other GUI window, so I'd look in that code first.

**Comment by Stibbons** [comment]
gsetting is only used to retrieve font when "use the system fixed width font". I don't reproduce this issue, the process isn't zombie avec prefs display, but I see there is no join/kill after using ``subprocess.Popen()``
