### ISSUE TITLE
Tabs bar size incorrect on hidpi screen

### ISSUE THREAD

**Issue by FallingSnow** [Guake/guake#728]
![screenshot from 2016-03-27 12-57-19](https://cloud.githubusercontent.com/assets/2512197/14067543/9c406d6e-f41b-11e5-9787-7d6ab04ca920.png)
I have a 4k display and the tabs only show about half the font.

**Comment by Stibbons** [comment]
Thanks for the report. Can you start guake through a terminal and copy paste the logs ?

**Comment by FallingSnow** [comment]
```
$ guake

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.

(guake:3161): libglade-WARNING **: unknown attribute `swapped' for <signal>.
INFO:guake.guake_app:Logging configuration complete
/usr/lib/python2.7/site-packages/guake/guake_app.py:1785: GtkWarning: gtk_box_pac
k: assertion 'child->parent == NULL' failed
  self.mainframe.pack_start(self.notebook, expand=True, fill=True, padding=0)
/usr/lib/python2.7/site-packages/guake/guake_app.py:825: GtkWarning: IA__gtk_wind
ow_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DOCK)
/usr/lib/python2.7/site-packages/guake/guake_app.py:826: GtkWarning: IA__gtk_wind
ow_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_NORMAL)
```

Like so?

**Comment by gazambuja** [comment]
Same problem here (Dell XPS 13 9343) any other test to do?

**Comment by boscowitch** [comment]
Same Problem on a Lenovo P50 with a 4k screen... I guess there is some scaling of the fonts underway in gnome and some apps also scale the buttons ect. but even the ones that do scale have too small icons most of the time.

**Comment by Stibbons** [comment]
sadly i dont have a 4k screen to test. But I also have an issue with HEAD, the size is wrong on the right of the screen. Look like old version of gtk does give the right screen size :(

**Comment by boscowitch** [comment]
Well to me it looks like GTK is doing the Button Size  right the width always fits and the heigth looks also good because the borders go out of the "toolbar" the only thing that is not size fitted is heith of the "toolbar" where the button is placed on. Either it is really a gtk bug, or it really is just that the size to content calculation come with a later event after the size of the "toolbar" is calculated and when the title of the button is set...  
btw. I run archlinux so It gtk should be pretty up to date since it's the most up to date distro i know here the packet version I have installed:  gtk2 2.24.30-1  and    gtk3 3.20.3-1

**Comment by boscowitch** [comment]
I played around a bit with the code... seems like GTK fails to adjust the size because RadioButtons are used with changed propertie, when i uncommented or changed bnt.set_property('draw-indicator', False) to True It size adjustment seems to work better ... unfortunately it looks ugly with radio buttons in front ;) 
![bildschirmfoto von 2016-04-17 10-48-43](https://cloud.githubusercontent.com/assets/252171/14586030/c356ebec-048a-11e6-8aa3-79c8fdfd3c8c.png)

**Comment by ehartford** [comment]
I had this issue when I changed the font size from the 10 point system default to a larger monofur powerline, the tab bar did not increase to accommodate the font size increase.

**Comment by ElvisPresly** [comment]
confirm
![2016-06-17 20-33-29](https://cloud.githubusercontent.com/assets/18265958/16159322/ceae0942-34ca-11e6-8a7a-8f2b0601100e.png)

**Comment by pylover** [comment]
+1

**Comment by omidraha** [comment]
I have the same issue:
![guake-728](https://cloud.githubusercontent.com/assets/397672/21523973/cdcd13d8-cd27-11e6-91da-38f17fe718d0.png)

**Comment by kmxm** [comment]
Here is a solution. I found out that height of the bar is hard-coded into glade UI descriptor file. I have removed height request letting gtk automatically set height accordingly to the content. So replace /ush/share/guake/*.glade files with attached.

[guake.zip](https://github.com/Guake/guake/files/712760/guake.zip)

**Comment by ehartford** [comment]
@kmxm  these files are [quite different](https://github.com/Guake/guake/compare/master...ehartford:master) from the ones currently in the repo.
If you could possibly do a PR with minimal changes to fix the height?

**Comment by Stibbons** [comment]
I let you deal with this, I mainly focus on guake 3 (gtk3 port) that requires full rewrite

**Comment by philmander** [comment]
To follow up on @kmxm 's comment, I just removed the line containing: `<property name="height_request">10</property>` in `/usr/share/guake/guake.glade`

This fixed the problem for me. I'm reluctant to make a PR because I have no idea if this would have any undesired consequences on other systems. I'm using a Dell XPI HiDPI screen with Ubuntu 16.04/Unity

**Comment by omidraha** [comment]
@philmander , Worked for me on the Kubuntu 16.04.3, 4k screen.

**Comment by FallingSnow** [comment]
This issue seems to resolved in version 0.8.9. Can anyone else confirm?

**Comment by olatov** [comment]
Started happening on the latest master to me again.
Seems to be caused by 29f6f328e73594d7e2d3706f81a03a24998c48a7

**Comment by Stibbons** [comment]
Can someone test with latest Guake 3 ?

**Comment by FallingSnow** [comment]
Seems to be fixed now.
