### ISSUE TITLE
Height issue moves Guake to non-primary screen

### ISSUE THREAD

**Issue by smith-and-web** [Guake/guake#770]
When Guake is set at 100% height it forces the terminal to the secondary screen. Probably because it exceeds the viewport size due to the top bar height.

Using Gnome 3.20, Ubuntu 16.04.

**Comment by koter84** [comment]
i think i have the same issue on Fedora 24, though with me it only happens if the screens have the same resolution. when i change resolution on one of the two screens the terminal opens where the mouse-pointer is.

i was still trying to debug what is going on, so i didn't report it yet, but seeing this issue i thought it's probably the same problem...

**Comment by koter84** [comment]
i made two debug logs, one with the two screens with the same resolution, one with different resolutions.
with the same resolution they are both 1920x1080 and the primary is on the left (screen 0)
with different resolutions the left one (primary, screen 0) is 1920x1080 and the one on the right is 1600x900, with the bottoms aligned.

[guake_same_resolution.txt](https://github.com/Guake/guake/files/359264/guake_same_resolution.txt)
[guake_different_resolution.txt](https://github.com/Guake/guake/files/359265/guake_different_resolution.txt)

there are some extra log.info() statements in my code, because i was trying to figure out why  this was happening, but i can't seem to figure it out...

**Comment by koter84** [comment]
i just found out that when i make the height less then 100% it does end up on the correct screen...

[guake_smaller.txt](https://github.com/Guake/guake/files/359270/guake_smaller.txt)

**Comment by koter84** [comment]
i found a workaround for this by moving the window_rect 27 pixels (my panel-size) when the destination screen is the primary screen...
i've been trying to find a way to detect the panel size to make it variable instead of a hard-coded 27 pixels.

this morning i found the window.maximize() function, and now i added a part which sets the size by maximize() when both the width and height percentage is set to 100.

https://github.com/Guake/guake/compare/master...koter84:debug?expand=1

i'll clean it up and make a pull request somewhere in the next couple of days

**Comment by Stibbons** [comment]
great!
