### ISSUE TITLE
Renamed tabs names are reset on new tab

### ISSUE THREAD

**Issue by micnic** [Guake/guake#804]
version: 0.8.7
Steps to reproduce:
- Open two tabs
- Rename both tabs
- Add a new tab
- (Renamed tabs have their names reset to their `cwd`)

**Comment by TheJavaGuy** [comment]
It still happens to me, guake 0.8.8, Ubuntu 14.04 LTS

**Comment by micnic** [comment]
@TheJavaGuy for me it is fine in Ubutnu 16.04 LTS, are you sure you are using 0.8.8?

**Comment by TheJavaGuy** [comment]
@micnic Unfortunately yes, it's 0.8.8. I attached 3 screenshots. First is about window, second is tab names before opening a new tab and third is tab names after opening a new tab. You can see that all tabs (except 2 named Misc1 and Misc2, very strange) are renamed to Terminal. It happens if I use shortcut Shift+Ctrl+T or if I right click and choose New Tab from menu.
![guake_about](https://cloud.githubusercontent.com/assets/11942401/20754958/886c39a2-b70d-11e6-878d-3b199db78702.png)
![guake_before_new_tab](https://cloud.githubusercontent.com/assets/11942401/20754960/886e89fa-b70d-11e6-9dd0-1457715965b4.png)
![guake_after_new_tab](https://cloud.githubusercontent.com/assets/11942401/20754959/886d5382-b70d-11e6-9194-c79b593c4f9c.png)

**Comment by Stibbons** [comment]
I cannot still reproduce, however I had a weird tab renaming at one point... and then I cannot reproduce again... Seems to be related to what you do on the tabs prior to this

**Comment by TheJavaGuy** [comment]
@Stibbons When "Use VTE titles for tab names" is on, undesired renaming happens. When it's off, everything works as expected.
