### ISSUE TITLE
No module named Exceptions

### ISSUE THREAD

**Issue by hong-duc** [Guake/guake#984]
It work fine yesterday, today I get this error, don't know why

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 43, in <module>
    from guake.guake_app import Guake
  File "/usr/lib/python2.7/dist-packages/guake/guake_app.py", line 41, in <module>
    import xdg.Exceptions
ImportError: No module named Exceptions
```

**Comment by Stibbons** [comment]
did you had an upgrade or a pip install done on your system ?

**Comment by hong-duc** [comment]
@Stibbons yes I use pip to install [tsrc](https://github.com/TankerApp/tsrc)

After restart, guake start error.
I remove pip and pip3, restart, reinstall guake. But the guake still error

**Comment by Stibbons** [comment]
that's the problem with installing any python application on the system through pip. You might break something. As a rule of thumb, always use a virtualenv. Guake should be installed system-wide with apt or your distribution package installer, or in a virtualenv. I know it is really hard since guake has so many system library dependencies.

**Comment by hong-duc** [comment]
@Stibbons how to revert this or clean it or something to make guake run again. I have uninstall tsrc but still cannot run guake

**Comment by hong-duc** [comment]
I uninstall all package installed by pip and it on again, thank you
