### ISSUE TITLE
Guake terminal does not drop down with F12

### ISSUE THREAD

**Issue by nathanaelmeister** [Guake/guake#994]
After a recent upgrade on my local Debian install Guake does not drop down by using `F12`

    Operating System: Debian GNU/Linux buster/sid
    Kernel: Linux 4.12.0-1-686-pae
    Architecture: x86
    Guake version: 0.8.8-1

once I started it manually I can call it with `F12`, but only on the virtual desktop where it was started, as soon as I change do a different desktop I can't call it with `F12` anymore.

As you can see on the screenshot, I'm on the 2ond desktop and in the bottom left the guake symbol shows up. I can call the terminal by clicking there with the mouse. But `F12` does not work.

![bildschirmfoto von 2017-08-26 01-44-35](https://user-images.githubusercontent.com/29178298/29736171-3e5e281e-89ff-11e7-922b-5e0917e36079.png)

If I start it from a terminal I get the following output:

```
(guake:3387): libglade-WARNING **: unknown attribute `swapped' for <signal>.
INFO:guake.guake_app:Logging configuration complete
/usr/lib/python2.7/dist-packages/guake/guake_app.py:865: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_DOCK)
/usr/lib/python2.7/dist-packages/guake/guake_app.py:866: GtkWarning: IA__gtk_window_set_type_hint: assertion '!gtk_widget_get_mapped (GTK_WIDGET (window))' failed
  self.window.set_type_hint(gtk.gdk.WINDOW_TYPE_HINT_NORMAL)
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 253, in <module>
    exec_main()
  File "/usr/lib/python2.7/dist-packages/guake/main.py", line 250, in exec_main
    gtk.main()
```

**Comment by xTeixeira** [comment]
Are you running on Xorg or Wayland?

**Comment by nathanaelmeister** [comment]
If I type this command:
 
> echo $XDG_SESSION_TYPE

I get this:

> wayland

so I assume it is wayland.

I found out that it makes a difference what kind of window is in the background:
- with Guake itself it works (close)
- with Firefox it works (open and close)
- with Frescobaldi it works (open and close)
- with gedit nothing works
- with no window nothing works, ets

Is there a way how to check if a window is using Wayland or X?

**Comment by xTeixeira** [comment]
Yes. That's the same behaviour as the issue I mentioned. It's the same one.
Every Gnome app uses Wayland, so that's why it doesn't work on gedit, nautilus, no window, etc.
Firefox (and most other non-gnome programs) are running on Wayland through XWayland, and in that case it will work.
The issue is that Guake uses a global hotkey library made for Xorg, and there is no interfaces in the Wayland specification yet for global hotkeys so that a similar library can be developed for Wayland.
The only workaround as of now is configuring hotkeys on your window manager of choice for opening and closing Guake as specified by [this](https://github.com/Guake/guake/issues/492#issuecomment-119075514) and [this](https://github.com/Guake/guake/issues/492#issuecomment-324165795) comment, the first one explaining the workaround and the second one providing a way to reduce the delay of guake opening and closing when using the provided workaround.
Another workaround is simply ditching Wayland entirely and choosing Gnome on Xorg as your session on GDM or whatever display manager you're using.

**Comment by nathanaelmeister** [comment]
thanks for the support, I'll close the issue.

**Comment by nstgc** [comment]
I have this issue as well, however I'm on X11.

In particular I'm using Arch and 
```
$ guake --version
Guake Terminal: 3.7.0
VTE: 0.60.3
VTE runtime: 0.60.3
Gtk: 3.24.21
```

I actually had this issue first on my laptop (also Arch), several months ago. I figured out that first opening the Guake preference menu fixes the issue. I don't actually need to DO anything, I just need to open it and can then close it again.

Also, starting a few months ago, Guake doesn't initially honor the "no scroll bar" setting. However, closing Guake (with F12) and then immediately reopening it (again with F12) fixes this, but it has to be done every time you start a new terminal or split an existing one.

**Comment by lain0** [comment]
same problem under Ubuntu 20.04.1 LTS
```
guake -V
Guake Terminal: 3.6.3
VTE: 0.60.3
VTE runtime: 0.60.3
Gtk: 3.24.20
```

$XDG_SESSION_TYPE:

```
echo $XDG_SESSION_TYPE
x11
```

**Comment by atanaschristov** [comment]
Same with me. Absolutely the same versions and settings. 

Ubuntu 20.04.1 LTE

**Comment by spyrosdev25** [comment]
same with me i am on ubuntu 20.04!
Also i tried to remove it with going to software & updates -> other software and removing it but it doesn't work, i also tried to delete all of their files

**Comment by spyrosdev25** [comment]
ok i think i found a solution to remove it :
you have to type in command sudo apt autoremove guake
now i am trying to install it and try again

**Comment by spyrosdev25** [comment]
ok i tried sudo apt-get install guake -y but the same prob again actually i tried to change the shortcuts like ctr alt 0 and stuff like that but nothing any suggestions about how to replace that or something?? i need it for a competitive programming tournament:)

**Comment by yairmark** [comment]
I found a nice workaround. Add a keyboard shortcut for it in the DE's keyboard shortcut settings. For example, in Gnome I set F12 to run Guake and it is working perfectly so far.

**Comment by clottes** [comment]
Seems the restore previous session is what is causing the issue of it not coming up as visible with F12 for me when I restart the machine.  With that option removed, it works fine... I'm just using x11 (fvwm).  Could be related, not enough time to diagnose, so just leaving those options off for now.

**Comment by clottes** [comment]
by the way if "guake -t" doesn't work "guake --show" should definitely bring it up.

**Comment by adostic** [comment]
I had the same issue on dell precision 5550 where guake will report issue with binding F12.
The problem is that on my keyboard you have to press Fn + End to get F12 and I had it locked so it default to F1-12. This caused the issue.

Changing keyboard setting in BIOS to default to F keys and not to `volume up`, `volume down`, and similar functions resolved the issue.

**Comment by nstgc** [comment]
To be clear, I'm using a normal, full-sized American keyboard without a Fn-key. It doesn't have any multimedia keys either. It's just a keyboard.

**Comment by joaquimbarreto** [comment]
> same problem under Ubuntu 20.04.1 LTS
> 
> ```
> guake -V
> Guake Terminal: 3.6.3
> VTE: 0.60.3
> VTE runtime: 0.60.3
> Gtk: 3.24.20
> ```
> 
> $XDG_SESSION_TYPE:
> 
> ```
> echo $XDG_SESSION_TYPE
> x11
> ```

Exactly same settings and Guake does not slide down

**Comment by R4xx4r** [comment]
I have the same problem on Ubuntu 21.04
```
guake -V
Guake Terminal: 3.6.3
VTE: 0.62.3
VTE runtime: 0.62.3
Gtk: 3.24.25

```

$XDG_SESSION_TYPE:
```
echo $XDG_SESSION_TYPE
wayland
```

My workaround is a custom keybinding to F12 via ubuntu intern keyboard shortcuts

**Comment by salehawal** [comment]
same here as well
wayland

**Comment by salehawal** [comment]
done i have set a shortcut using ubuntu system
![Screenshot from 2021-11-04 16-45-49](https://user-images.githubusercontent.com/3238761/140335296-fa4d130c-14c9-4bc8-a27a-150199e62ade.png)

**Comment by sebaxtian** [comment]
> done i have set a shortcut using ubuntu system ![Screenshot from 2021-11-04 16-45-49](https://user-images.githubusercontent.com/3238761/140335296-fa4d130c-14c9-4bc8-a27a-150199e62ade.png)

Hi, this is the best solution for me, thanks @salehawal , because it isn't necessary to change the **$XDG_SESSION_TYPE** and continue using **wayland** session type on **Linux/Ubuntu**:

```
sebaxtian@Voyager:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

```
sebaxtian@Voyager:~$ echo $XDG_SESSION_TYPE
wayland
```

```
sebaxtian@Voyager:~$ guake --version
Guake Terminal: 3.8.5
VTE: 0.68.0
VTE runtime: 0.68.0
Gtk: 3.24.33
```


**Step 1**:
**_Open Settings -> Keyboard_**
![image](https://user-images.githubusercontent.com/695945/218238122-586fa4e5-0adf-4c4f-98bd-dd1ed23ea87e.png)

**Step 2**:
Click on **_View and Customize Shortcuts_**, then on the new open window scroll down and click on **_Custom Shortcuts_**
![image](https://user-images.githubusercontent.com/695945/218238196-6babf0fd-4190-4826-9b04-f5c082e182e8.png)

**Step 3**:
Add new **_Custom Shortcuts_** by clicking on the **_+_** symbol and set up the same shortcut that you assigned on Guake settings, please be careful and the Guake command should be: **_guake-toggle_**
![image](https://user-images.githubusercontent.com/695945/218238315-0fd3d2a2-3070-4b4f-bfa0-e846b2cba1d5.png)

**Finally, enjoy your Guake Terminal anywhere** ...

Regards @sebaxtian
